# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b47a4bd30d2c5e492ba7c22d03ee647eba2b1f1b6e4294dd5b4acb6415bc4a59832f6f97191c65a24d46f4a68b2831c6b6edec04180c4a881ede74869fd19501

test:
  secret_key_base: 0635dd7a40364e096ecd9ad5a23a52a1d6e814687f6f700a9da1b43640d8304aa8b385c6c50560227712485fe114d224bde57da54186eb03b2ef43ba72612087

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
